name: Update overlay using Superflore
on:
  schedule:
    - cron: "0 12 * * FRI"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: wentasah
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install Superflore
        run: |
          nix-env -f . -iA python3Packages.rosdep superflore
      - name: Update overlay
        env:
          # Don't use secrets.GITHUB_TOKEN because it prevents the PR from
          # triggering a build
          # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events
          SUPERFLORE_GITHUB_TOKEN: ${{ secrets.SUPERFLORE_GITHUB_TOKEN }}
          ROS_OS_OVERRIDE: nixos
          ROSDEP_SOURCE_PATH: rosdep-sources
        run: |
          mkdir -p "$ROSDEP_SOURCE_PATH"
          curl https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list -o "$ROSDEP_SOURCE_PATH/20-default.list"
          rosdep update
          git config --local user.email "superflore@github.com"
          git config --local user.name "Superflore"
          git config credential.helper '!
            f() {
              echo "username=lopsided98"
              echo "password=${SUPERFLORE_GITHUB_TOKEN}"
            }; f'
          superflore-gen-nix --dry-run \
            --tar-archive-dir "${{ runner.temp }}/tar" \
            --output-repository-path . \
            --upstream-branch develop \
            --ros-distro jazzy
      - name: Update ament_vendor info
        run: |
          NIX_PATH=nixpkgs=$PWD ./maintainers/scripts/update-ament-vendor.sh -1
          git commit -m 'Update vendored-source.json files' $(find -name vendored-source.json) || :
      - name: Create PR
        run: |
          superflore-gen-nix --pr-only \
            --output-repository-path .
